[package]
name = "red-lox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"

[workspace]
members = ["red-lox-ast", "red-lox-interpreter"]

[workspace.dependencies]
red-lox-ast = {path = "red-lox-ast"}
thiserror = "2.0.9"
