[package]
name = "red-lox-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
red-lox-ast = {workspace=true}
thiserror = {workspace=true}
anyhow = {workspace=true}