[package]
name = "red-lox-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
phf = { version="0.11", features = ["macros"] }
thiserror = {workspace = true}

[dev-dependencies]
rstest = {workspace = true}
googletest = {workspace = true}
